name: Deploy Hospital API

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEB_APP_NAME: 'hospitalvisitsexerciseapi'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build

      - name: Publish
        run: dotnet publish --no-build --output ./publish

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEB_APP_NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish

      - name: Set connection string
        run: |
          az webapp config connection-string set \
            --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
            --name ${{ env.AZURE_WEB_APP_NAME }} \
            --connection-string-type SQLAzure \
            --settings HospitalDb=${{ secrets.HOSPITAL_DB_CONNECTION_STRING }}

      - name: Azure logout
        run: az logout